# Generated by Django 2.2.7 on 2020-03-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_name', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
